library(readr)
library(here)

dat <- read_csv(here("data/full_deidentified_data.csv"))

subspecialty <- c(
  "ANESTESIOLOGIA CARDIOVASCULAR", "CIRUGIA COLORECTAL",
  "CIRUGIA DE COLON, RECTO Y ANO", "CIRUGIA DE MANO", "CIRUGIA DE RETINA Y VITREO",
  "CIRUGIA DE TORAX ONCOLOGICA", "CIRUGIA HEPATOPANCREATOBILIAR Y TRANSPLANTE",
  "CIRUGIA ONCOLOGICA ABDOMINAL", "CIRUGIA ONCOLOGICA DE CABEZA Y CUELLO",
  "CIRUGIA ONCOLOGICA DE MAMAS, TEJIDOS", "CIRUGIA ONCOLOGICA DE MAMAS, TEJIDOS BLANDOS Y PIEL",
  "CIRUGIA ONCOLOGICA GINECOLOGICA", "NEUMOLOGIA ONCOLOGICA",
  "OFTALMOLOGIA ONCOLOGICA", "PATOLOGIA ONCOLOGICA", "PSIQUIATRIA DE ADICCIONES",
  "RADIOLOGIA INTERVENCIONISTA", "UROLOGIA ONCOLOGICA", "CIRUGIA CARDIOVASCULAR PEDIATRICA",
  "CARDIOLOGIA PEDIATRICA", "ENDOCRINOLOGIA PEDIATRICA", "GASTROENTEROLOGIA PEDIATRICA",
  "GINECOLOGIA ONCOLOGICA", "HEMATOLOGIA PEDIATRICA", "MEDICINA INTENSIVA PEDIATRICA",
  "INFECTOLOGIA PEDIATRICA", "NEFROLOGIA PEDIATRICA", "NEONATOLOGIA", "NEUMOLOGIA PEDIATRICA",
  "NEUROCIRUGIA PEDIATRICA", "NEUROLOGIA PEDIATRICA", "ONCOLOGIA PEDIATRICA",
  "PSIQUIATRIA DEL NIÑO Y DEL ADOLESCENTE", "UROLOGIA PEDIATRICA",
  "OFTALMOLOGIA PEDIATRICA Y ESTRABISMO", "DERMATOLOGIA PEDIATRICA"
)

dat$subespecialidad <- ifelse(dat$especialidad %in% subspecialty, 1, 0)
write_csv(dat, here("data/full_deidentified_data.csv"))
